#!/bin/bash
echo Saving container logs...
touch error.log output.log
docker logs seba 2>> error.log 1>> output.log

docker build -t mtsev/seba .

echo Delete old container...
docker rm -f seba

echo Run new container...
docker run -d \
	--network host \
	--name seba \
	--restart=always \
	-e TZ=Australia/Sydney \
	mtsev/seba
