#!/bin/bash
echo Saving container logs...
touch logs
docker logs seba >> logs

docker build -t mtsev/seba .

echo Delete old container...
docker rm -f seba

echo Run new container...
docker run -d \
	--network host \
	--name seba \
	--restart=always \
	-e TZ=Australia/Sydney \
	mtsev/seba
